# Generated by Django 4.2.7 on 2024-02-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_lesson_video_url'),
        ('users', '0003_alter_payment_paid_course_alter_payment_paid_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_lesson',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paid_course',
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_course',
            field=models.ManyToManyField(blank=True, null=True, to='materials.course', verbose_name='paid_course'),
        ),
    ]
