# Generated by Django 4.2.7 on 2024-02-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_payment_paid_lesson_remove_payment_paid_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Moderator', 'Moderator'), ('User', 'User')], default='User', verbose_name='role'),
        ),
    ]
