# Generated by Django 4.2.7 on 2024-02-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
