# Generated by Django 4.2.7 on 2024-03-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_payment_payment_id_payment_payment_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid_lesson',
        ),
    ]
