# Generated by Django 4.2.7 on 2024-03-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_payment_paid_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.IntegerField(default=30000, verbose_name='value'),
        ),
    ]
