# Generated by Django 4.2.7 on 2024-03-17 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_payment_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'payment', 'verbose_name_plural': 'payments'},
        ),
    ]
