# Generated by Django 4.2.7 on 2024-03-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_payment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, null=True, verbose_name='status'),
        ),
    ]
