# Generated by Django 4.2.7 on 2024-03-17 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='price')),
                ('payment_link', models.URLField(blank=True, max_length=400, null=True, verbose_name='payment_link')),
                ('payment_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='payment_id')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
            },
        ),
    ]
