# Generated by Django 4.2.7 on 2024-03-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0005_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
